apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-back-end
  labels:
    app: react-back-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-back-end
  template:
    metadata:
      labels:
        app: react-back-end
    spec:
      containers:
      - name: react-back-end
        image: prathod1995/react-back-end
        ports:
        - containerPort: 8001

