apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react-front-end
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
        
